import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { HeaderMiddle } from 'components/headerMiddle'
import { FooterSocial } from 'components/footerSocial'
import { HeroBullets } from 'components/heroBullets'
import { UserCardImage } from 'components/userCardImage'
import { IntroductionImages } from 'components/introductionImages'
import { ProjectsCardsGrid } from 'components/projectsCardsGrid'
import { headersConfig, profile, introductionData } from 'config/information'

export default function About() {
  return (
    <>
      <Head>
        <title>SimflexCloud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HeaderMiddle links={headersConfig.links} />
        <div className={styles.profile}>
        <UserCardImage 
          avatar={profile.avatar} 
          image={profile.image} 
          name={profile.name} 
          email={profile.email} 
          job={profile.job}
          stats={profile.stats}
        />
        </div>
        <IntroductionImages 
          supTitle={introductionData.supTitle}
          description={introductionData.description} 
          data={introductionData.data} 
        />
        <ProjectsCardsGrid />
        <FooterSocial />
      </main>
    </>
  )
}
