import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { HeaderMiddle } from 'components/headerMiddle'
import { headersConfig } from 'mockData/ui'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>SimflexCloud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HeaderMiddle links={headersConfig.links} />
        <div className={styles.center}>
          <h1>Welcome to SimflexCloud</h1>
        </div>
      </main>
    </>
  )
}
